// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function StartServer(arg1:number,arg2:number):Promise<void>;

export function StopServer():Promise<void>;
