// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function StartServer(arg1, arg2) {
  return window['go']['main']['App']['StartServer'](arg1, arg2);
}

export function StopServer() {
  return window['go']['main']['App']['StopServer']();
}
