// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetMessage():Promise<string>;

export function GetSignal():Promise<boolean>;

export function SendMessage(arg1:string):Promise<string>;

export function SendSignal():Promise<string>;

export function StartClient(arg1:string,arg2:string,arg3:number):Promise<number>;

export function StopClient():Promise<void>;
