// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetMessage() {
  return window['go']['main']['App']['GetMessage']();
}

export function GetSignal() {
  return window['go']['main']['App']['GetSignal']();
}

export function SendMessage(arg1) {
  return window['go']['main']['App']['SendMessage'](arg1);
}

export function SendSignal() {
  return window['go']['main']['App']['SendSignal']();
}

export function StartClient(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartClient'](arg1, arg2, arg3);
}

export function StopClient() {
  return window['go']['main']['App']['StopClient']();
}
